export const CREATE_GAME = 'games/CREATE_GAME';
export const GAME_CREATED = 'games/GAME_CREATED';
export const END_GAME = 'games/END_GAME';

export const DECLARE_GAME_DRAW = 'games/GAME_DECLARE_DRAW';
export const DECLARE_GAME_VICTORY = 'games/GAME_DECLARE_VICTORY';

export const EXECUTE_MOVE_REQUEST = 'games/EXECUTE_MOVE_REQUEST';
export const EXECUTE_MOVE_SUCCESS = 'games/EXECUTE_MOVE_SUCCESS';
export const EXECUTE_MOVE_FAILURE = 'games/EXECUTE_MOVE_FAILURE';

export const PLAYER_TURN_REQUEST = 'games/PLAYER_TURN_REQUEST';
export const PLAYER_TURN_FAILURE = 'games/PLAYER_TURN_FAILURE';
export const PLAYER_TURN_STARTED = 'games/PLAER_TURN_STARTED';

export const FETCH_GAMES_REQUEST = 'games/FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'games/FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'games/FETCH_GAMES_FAILURE';
export const FETCH_GAMES_NONE_FOUND = 'games/FETCH_GAMES_NONE_FOUND';

export const UPDATE_GAME_REQUEST = 'games/UPDATE_GAME_REQUEST';
export const UPDATE_GAME_SUCCESS = 'games/UPDATE_GAME_SUCCESS';
export const UPDATE_GAME_FAILURE = 'games/UPDATE_GAME_FAILURE';

export const TOGGLE_CREATE_GAME_DIALOG = "games/TOGGLE_CREATE_GAME_DIALOG";

export const REQUEST_PRACTICE_GAME = "games/REQUEST_PRACTICE_GAME";

